# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    labels: ["deps", "pip"]
    reviewers: ["Guffawaffle"]
    groups:
      prod-deps:
        applies-to: version-updates
        update-types: ["minor", "patch"]
      security-updates:
        applies-to: security-updates

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "gha"]

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule: { interval: "weekly" }
    open-pull-requests-limit: 5
    labels: ["deps", "npm"]
