---
# Author: Lex (AI assistant), requested by @guff — 2025-09-13
name: Dependency Review

"on":
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: true
