name: Preexec Guard

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  grep-preexec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grep for preexec_fn
        run: |
          set -euo pipefail
          # Scope to project sources; exclude vendored dirs if added later
          if git grep -n "preexec_fn=" -- 'loquilex/**/*.py' ':!loquilex/vendor/**' | tee /tmp/preexec_matches; then
            echo "preexec_fn occurrences found:" >&2
            cat /tmp/preexec_matches >&2
            exit 1
          else
            echo "No preexec_fn found under loquilex/"
          fi
