name: Preexec Guard

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  grep-preexec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grep for preexec_fn
        run: |
          set -euo pipefail
          # Repo-wide scan of tracked Python files; exclude common vendor/venv paths
          if git grep -n -E "preexec_fn\s*=" -- "**/*.py" \
               ':!**/.venv/**' ':!**/node_modules/**' ':!**/vendor/**' ':!**/.git/**' | tee /tmp/preexec_matches; then
            echo "::error::preexec_fn occurrences found:" >&2
            cat /tmp/preexec_matches >&2
            exit 1
          else
            echo "No preexec_fn found in tracked Python sources"
          fi
